version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store_ch
      - POSTGRES_USER=charles
      - POSTGRES_PASSWORD=ch080
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
  mysql:
    platform: linux/x86_64
    image: mysql:5
    environment:
        - MYSQL_DATABASE=my_store_ch
        - MYSQL_ROOT_PASSWORD=ch080
        - MYSQL_PORT=3306
    ports:
        - 3306:3306
    volumes:
        - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    platform: linux/x86_64
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=ch080
      - PMA_HOST=mysql
    ports:
      - 8080:80

