version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store_ch
      - POSTGRES_USER=charles
      - POSTGRES_PASSWORD=ch080
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    

    